replicaCount: 1

image:
  repository: faisalkamil/flask_app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: ""
  path: /
  hosts:
    - host: myapp.local
      paths:
        - /
  tls: []
